name: Run The Tests
on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Unit Testing
      run: |
        cd ciphers_project
        python manage.py test
    - name: Build Image and push to registry
      run: |
        docker login --username saisathwikreddy --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/saisathwikreddy/cipher-service:latest --file Dockerfile .  
                docker push ghcr.io/saisathwikreddy/cipher-service:latest 